# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initlslinreg <- function(y, xl, xtx, ql, rtl, k, zt, resids, s2) {
    .Call(`_LinGxEScanR_initlslinreg`, y, xl, xtx, ql, rtl, k, zt, resids, s2)
}

lslinreg <- function(dosage, y, xl, xr, xtx, bt, bb, ql, qr, rtl, rtr, rbr, h, k, t, zb, resids, s2, xtxinv, std_err, xrs2, chi2) {
    .Call(`_LinGxEScanR_lslinreg`, dosage, y, xl, xr, xtx, bt, bb, ql, qr, rtl, rtr, rbr, h, k, t, zb, resids, s2, xtxinv, std_err, xrs2, chi2)
}

initreg <- function(X, y) {
    .Call(`_LinGxEScanR_initreg`, X, y)
}

