# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initlslinreg <- function(y, x) {
    .Call(`_LinGxEScanR_initlslinreg`, y, x)
}

lslinreg <- function(y, xl, xr, xtx, bt, bb, ql, qr, rtl, rtr, rbr, h, k, t, zb, res, s2, xtxinv, std_err, xrS2, xrChi2) {
    .Call(`_LinGxEScanR_lslinreg`, y, xl, xr, xtx, bt, bb, ql, qr, rtl, rtr, rbr, h, k, t, zb, res, s2, xtxinv, std_err, xrS2, xrChi2)
}

initreg <- function(X, y) {
    .Call(`_LinGxEScanR_initreg`, X, y)
}

